sandbox_mode = "read-only"
approval_policy = "on-request"
approvals_reviewer = "user"
oss_provider = "litellm"

[features.multi_agent_v2]
enabled = true
hide_spawn_agent_metadata = false
tool_namespace = "agents"

[tui]
whimsy = false
status_line = ["current-dir", "model-with-reasoning", "context-used", "five-hour-limit", "weekly-limit", "permissions", "approval-mode"]
status_line_use_colors = true

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

[model_providers.llama_cpp]
name = "llama.cpp"
base_url = "http://localhost:9931/v1"
requires_openai_auth = false

[model_providers.litellm]
name = "LiteLLM"
base_url = "http://localhost:4000/v1"
requires_openai_auth = false
