litellm_settings:
  drop_params: true

model_list:
  - model_name: "llama_cpp/*"
    litellm_params:
      model: "openai/*"
      api_base: "http://127.0.0.1:9931/v1"
      api_key: "unused"
      use_chat_completions_api: true

  - model_name: "github_copilot/*"
    litellm_params:
      model: "github_copilot/*"
      extra_headers: {
        "editor-version": "vscode/1.104.1",
        "editor-plugin-version": "copilot/1.155.0",
        "Copilot-Integration-Id": "vscode-chat",
        "user-agent": "GithubCopilot/1.155.0"
      }

  - model_name: "chatgpt/*"
    model_info:
      mode: responses
    litellm_params:
      model: "chatgpt/*"

  # fallback
  - model_name: "*"
    litellm_params:
      model: "*"
