#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
if ! test "$SSH_AUTH_SOCK" ; then
    export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
fi

ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
